import type { Metadata } from "next";

import "./globals.css";
import { Header } from "@/components/Header/Header";
import { Body } from "@/components/Body/Body";
import styles from "./layout.module.css";
import { AppProvider } from "@/context/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AppProvider>
        <Body>
          <Header />
          <main className={styles.main}>{children}</main>
        </Body>
      </AppProvider>
    </html>
  );
}
