import type { Metadata } from "next";
import {
  SlussenMedium,
  SlussenMonoMedium,
  MonumentExtended,
} from "@/fonts/fonts";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import styles from "./layout.module.css";
import { AppProvider } from "@/context/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${SlussenMedium.variable} ${SlussenMonoMedium.variable} ${MonumentExtended.variable}`}
      >
        <AppProvider>
          <Header />
          <main className={styles.main}>{children}</main>
        </AppProvider>
      </body>
    </html>
  );
}
