import type { Metadata } from "next";
import { SlussenMedium, SlussenMonoMedium } from "@/fonts/fonts";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${SlussenMedium.variable} ${SlussenMonoMedium.variable}`}
      >
        <Header />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
